#欢迎来到SliderProxy配置文件，您可以在此处配置您的代理

#代理设置
proxy:
  host: "0.0.0.0" # 代理服务器监听地址
  port: 25565 # 代理服务器启动端口
  force-default-server: false # 是否强制将玩家发送到第一个服务器（无论其是否加入过代理）
  default-server: lobby # 如果玩家第一次加入代理，则将其发送到的服务器
  bungeecord-plugin-message: false # 是否启用BungeeCord插件消息通道
  ip-forward: false # 是否启用IP转发
  delay-forward: true # 是否启用延迟转发
  online-mode: true # 是否启用在线模式
  motd: "SliderProxy - 欢迎来到SliderProxy!" # 服务器列表显示的 MOTD (可使用\n换行)
  max-players: 20 # 服务器列表显示的最大玩家数
  real-max-players: false # max-players设置是否真的是最大人数(如设为false则玩家加入时满人也可以加入，否则会拒绝加入)
  compress-threshold: 256 # 启用数据包压缩的阈值

#子服务器设置
servers:
  lobby:
    address: "127.0.0.1" # 子服务器地址
    port: 25566 # 子服务器端口
  example2:
    address: "127.0.0.1"
    port: 25567